### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nevillelyh** [nevillelyh/scio-koans#1]
- [x] `DoFn`
- [x] `combine/aggregate` with mutation
- [x] Approximate algorithms
- [ ] More join/cogroup Koans
- [x] Java vs Scala primitives
